package org.mtr.mapping.test;

import net.minecraft.block.Block;
import net.minecraft.block.BlockState;
import net.minecraft.block.SlabBlock;
import net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher;
import net.minecraft.client.util.ITooltipFlag;
import net.minecraft.client.world.ClientWorld;
import net.minecraft.dispenser.IPosition;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.LivingEntity;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.entity.player.ServerPlayerEntity;
import net.minecraft.fluid.FluidState;
import net.minecraft.item.BlockItemUseContext;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.item.ItemUseContext;
import net.minecraft.nbt.CompoundNBT;
import net.minecraft.network.PacketBuffer;
import net.minecraft.scoreboard.Scoreboard;
import net.minecraft.state.*;
import net.minecraft.tileentity.TileEntity;
import net.minecraft.tileentity.TileEntityType;
import net.minecraft.util.*;
import net.minecraft.util.math.AxisAlignedBB;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.BlockRayTraceResult;
import net.minecraft.util.math.MathHelper;
import net.minecraft.util.math.shapes.ISelectionContext;
import net.minecraft.util.math.shapes.VoxelShape;
import net.minecraft.util.math.shapes.VoxelShapes;
import net.minecraft.util.math.vector.Vector3d;
import net.minecraft.util.math.vector.Vector3f;
import net.minecraft.util.math.vector.Vector3i;
import net.minecraft.util.text.IFormattableTextComponent;
import net.minecraft.util.text.ITextComponent;
import net.minecraft.util.text.TextFormatting;
import net.minecraft.world.*;
import net.minecraft.world.chunk.AbstractChunkProvider;
import net.minecraft.world.chunk.Chunk;
import net.minecraft.world.gen.Heightmap;
import net.minecraft.world.server.ServerWorld;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.util.Random;

public final class GenerateHoldersTest {

	@Test
	public void generate() throws IOException {
		final GenerateHolders generateHolders = new GenerateHolders();
		generateHolders.put("ActionResult", ActionResultType.class);
		generateHolders.put("Axis", Direction.Axis.class);
		generateHolders.put("BlockEntityRendererArgument", TileEntityRendererDispatcher.class);
		generateHolders.put("BlockEntityType", TileEntityType.class);
		generateHolders.put("BlockHitResult", BlockRayTraceResult.class);
		generateHolders.put("BlockPos", BlockPos.class);
		generateHolders.put("BlockState", BlockState.class);
		generateHolders.put("BlockView", IBlockReader.class);
		generateHolders.put("BooleanProperty", BooleanProperty.class);
		generateHolders.put("Box", AxisAlignedBB.class);
		generateHolders.put("ChunkManager", AbstractChunkProvider.class);
		generateHolders.put("ClientWorld", ClientWorld.class);
		generateHolders.put("CompoundTag", CompoundNBT.class);
		generateHolders.put("Direction", Direction.class);
		generateHolders.put("DirectionProperty", DirectionProperty.class);
		generateHolders.put("EntityType", EntityType.class);
		generateHolders.put("EnumProperty", EnumProperty.class);
		generateHolders.put("Explosion", Explosion.class);
		generateHolders.put("FluidState", FluidState.class);
		generateHolders.put("Hand", Hand.class);
		generateHolders.put("HeightMapType", Heightmap.Type.class);
		generateHolders.put("IntegerProperty", IntegerProperty.class);
		generateHolders.put("ItemPlacementContext", BlockItemUseContext.class);
		generateHolders.put("ItemStack", ItemStack.class);
		generateHolders.put("ItemUsageContext", ItemUseContext.class);
		generateHolders.put("LivingEntity", LivingEntity.class);
		generateHolders.put("MathHelper", MathHelper.class);
		generateHolders.put("Mirror", Mirror.class);
		generateHolders.put("MutableText", IFormattableTextComponent.class);
		generateHolders.put("OrderedText", IReorderingProcessor.class);
		generateHolders.put("PacketBuffer", PacketBuffer.class);
		generateHolders.put("PlayerEntity", PlayerEntity.class);
		generateHolders.put("Position", IPosition.class);
		generateHolders.put("Property", Property.class);
		generateHolders.put("Random", Random.class);
		generateHolders.put("ResourceLocation", ResourceLocation.class);
		generateHolders.put("Rotation", Rotation.class);
		generateHolders.put("Scoreboard", Scoreboard.class);
		generateHolders.put("ServerPlayerEntity", ServerPlayerEntity.class);
		generateHolders.put("ServerWorld", ServerWorld.class);
		generateHolders.put("ServerWorldAccess", IServerWorld.class);
		generateHolders.put("ShapeContext", ISelectionContext.class);
		generateHolders.put("SoundCategory", SoundCategory.class);
		generateHolders.put("SoundEvent", SoundEvent.class);
		generateHolders.put("Text", ITextComponent.class);
		generateHolders.put("TextFormatting", TextFormatting.class);
		generateHolders.put("TooltipContext", ITooltipFlag.class);
		generateHolders.put("Vector3d", Vector3d.class);
		generateHolders.put("Vector3f", Vector3f.class);
		generateHolders.put("Vector3i", Vector3i.class);
		generateHolders.put("VoxelShape", VoxelShape.class);
		generateHolders.put("VoxelShapes", VoxelShapes.class);
		generateHolders.put("World", World.class);
		generateHolders.put("WorldAccess", IWorld.class);
		generateHolders.put("WorldChunk", Chunk.class);
		generateHolders.putAbstract("Block", Block.class);
		generateHolders.putAbstract("BlockEntity", TileEntity.class);
		generateHolders.putAbstract("Entity", Entity.class);
		generateHolders.putAbstract("Item", Item.class);
		generateHolders.putAbstract("SlabBlock", SlabBlock.class);
		generateHolders.generate();
	}
}
