package org.mtr.mapping;

public interface MethodMaps {

	static void setMethodMaps() {
		BuildTools.addMethodMap1("Block|SlabBlock", "emitsRedstonePower", "isSignalSource");
		BuildTools.addMethodMap1("Block|SlabBlock", "getInteractionShape", "getRaycastShape");
		BuildTools.addMethodMap1("Block|SlabBlock", "getOcclusionShape", "getCullingShape");
		BuildTools.addMethodMap1("Block|SlabBlock", "getOutlineShape", "getShape");
		BuildTools.addMethodMap1("Block|SlabBlock", "getSidesShape", "getBlockSupportShape");
		BuildTools.addMethodMap1("Block|SlabBlock", "getStrongRedstonePower", "getDirectSignal");
		BuildTools.addMethodMap1("Block|SlabBlock", "getVisualShape", "getCameraCollisionShape");
		BuildTools.addMethodMap1("Block|SlabBlock", "getWeakRedstonePower", "getSignal");
		BuildTools.addMethodMap1("Block|SlabBlock", "hasComparatorOutput", "hasAnalogOutputSignal");
		BuildTools.addMethodMap1("Block|SlabBlock", "hasRandomTicks", "isRandomlyTicking");
		BuildTools.addMethodMap1("Block|SlabBlock", "isTranslucent", "isTransparent", "propagatesSkylightDown");
		BuildTools.addMethodMap1("Block|SlabBlock", "onPlace", "onBlockAdded");
		BuildTools.addMethodMap1("Block|SlabBlock", "onRemove", "onStateReplaced");
		BuildTools.addMethodMap1("BlockEntity", "markDirty", "setChanged");
		BuildTools.addMethodMap1("BlockEntity", "markRemoved", "setRemoved");
		BuildTools.addMethodMap1("BlockItem|Item", "hasGlint", "isFoil");
		BuildTools.addMethodMap1("BlockItem|Item", "isFood", "isEdible");
		BuildTools.addMethodMap1("BlockItem|Item", "isNbtSynced", "shouldOverrideMultiplayerNbt", "shouldSyncTagToClient");
		BuildTools.addMethodMap1("BlockItem|Item", "isNetworkSynced", "isComplex");
		BuildTools.addMethodMap1("BlockPos", "crossProduct", "cross");
		BuildTools.addMethodMap1("BlockPos", "down", "below");
		BuildTools.addMethodMap1("BlockPos", "toImmutable", "immutable");
		BuildTools.addMethodMap1("BlockPos", "up", "above");
		BuildTools.addMethodMap2("BlockState", "prepare", "public final void (WorldAccess,BlockPos,int)", "updateIndirectNeighbourShapes");
		BuildTools.addMethodMap2("BlockState", "updateNeighbors", "public final void (WorldAccess,BlockPos,int)", "updateNeighbourShapes");
		BuildTools.addMethodMap1("BlockState", "with", "setValue");
		BuildTools.addMethodMap1("BooleanProperty|EnumProperty|IntegerProperty", "of", "create");
		BuildTools.addMethodMap1("CompoundTag", "getSize", "size");
		BuildTools.addMethodMap1("Direction", "byId", "from2DDataValue");
		BuildTools.addMethodMap1("Direction", "fromHorizontal", "from3DDataValue");
		BuildTools.addMethodMap1("Direction", "getHorizontal", "get2DDataValue");
		BuildTools.addMethodMap1("Direction", "getId", "get3DDataValue");
		BuildTools.addMethodMap1("Direction", "getOffsetX", "getStepX");
		BuildTools.addMethodMap1("Direction", "getOffsetY", "getStepY");
		BuildTools.addMethodMap1("Direction", "getOffsetZ", "getStepZ");
		BuildTools.addMethodMap1("Direction", "pointsTo", "isFacingAngle", "method_30928");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "addScoreboardTag", "addCommandTag", "addTag");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "getArmorItems", "getArmorSlots");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "getBlockPos", "blockPosition");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "getBodyY", "getY");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "getEntityName", "getScoreboardName");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "getEntityWorld", "getCommandSenderWorld");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "getHandItems", "getHandSlots", "getItemsHand");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "getHeightOffset", "getMyRidingOffset");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "getHorizontalFacing", "getDirection");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "getItemsEquipped", "getAllSlots");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "getMountedHeightOffset", "getPassengersRidingOffset");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "getMovementDirection", "getMotionDirection");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "getParticleX", "getRandomX");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "getParticleZ", "getRandomZ");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "getRandomBodyY", "getRandomY");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "getSwimHeight", "getFluidJumpThreshold", "method_29241");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "getUuidAsString", "getStringUUID");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "isSneaking", "isShiftKeyDown");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "offsetX", "getX");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "offsetZ", "getZ");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "removeScoreboardTag", "removeTag");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "setBodyYaw", "setYBodyRot");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "setHeadYaw", "setYHeadRot");
		BuildTools.addMethodMap1("Entity|PlayerEntity|ServerPlayerEntity", "tickRiding", "rideTick");
		BuildTools.addMethodMap1("ItemPlacementContext", "canReplaceExisting", "replacingClickedOnBlock");
		BuildTools.addMethodMap1("ItemPlacementContext", "getClickedFace", "getSide");
		BuildTools.addMethodMap1("ItemPlacementContext", "getPlayerFacing", "getHorizontalPlayerFacing", "getHorizontalDirection");
		BuildTools.addMethodMap1("ItemPlacementContext", "getPlayerLookDirection", "getNearestLookingDirection");
		BuildTools.addMethodMap1("ItemPlacementContext", "hitsInsideBlock", "isInside");
		BuildTools.addMethodMap1("ItemPlacementContext", "shouldCancelInteraction", "isSecondaryUseActive");
		BuildTools.addMethodMap1("ItemStack", "decrement", "shrink");
		BuildTools.addMethodMap1("ItemStack", "getOrCreateTag", "getOrCreateNbt");
		BuildTools.addMethodMap1("ItemStack", "getTag", "getNbt");
		BuildTools.addMethodMap1("ItemStack", "increment", "grow");
		BuildTools.addMethodMap1("ItemUsageContext", "getHorizontalPlayerFacing", "getHorizontalDirection", "getPlayerFacing");
		BuildTools.addMethodMap1("ItemUsageContext", "getSide", "getClickedFace");
		BuildTools.addMethodMap1("ItemUsageContext", "hitsInsideBlock", "isInside");
		BuildTools.addMethodMap1("ItemUsageContext", "shouldCancelInteraction", "isSecondaryUseActive");
		BuildTools.addMethodMap1("PlayerEntity|ServerPlayerEntity", "getMainHandStack", "getMainHandItem");
		BuildTools.addMethodMap1("Scoreboard", "addTeam", "addPlayerTeam");
		BuildTools.addMethodMap1("Scoreboard", "clearPlayerTeam", "removePlayerFromTeam");
		BuildTools.addMethodMap1("Scoreboard", "containsObjective", "hasObjective");
		BuildTools.addMethodMap1("Scoreboard", "forEachScore", "forAllObjectives");
		BuildTools.addMethodMap1("Scoreboard", "getObjectives");
		BuildTools.addMethodMap1("Scoreboard", "getTeam", "getPlayersTeam");
		BuildTools.addMethodMap1("Scoreboard", "removeTeam", "removePlayerTeam");
		BuildTools.addMethodMap1("Scoreboard", "updateExistingObjective", "onObjectiveChanged");
		BuildTools.addMethodMap1("Scoreboard", "updateObjective", "onObjectiveAdded");
		BuildTools.addMethodMap1("Scoreboard", "updateRemovedObjective", "onObjectiveRemoved");
		BuildTools.addMethodMap1("Scoreboard", "updateRemovedTeam", "onTeamRemoved");
		BuildTools.addMethodMap1("Scoreboard", "updateScoreboardTeam", "onTeamChanged");
		BuildTools.addMethodMap1("Scoreboard", "updateScoreboardTeamAndPlayers", "onTeamAdded");
		BuildTools.addMethodMap1("ScoreboardCriterion", "getOrCreateStatCriterion", "byName");
		BuildTools.addMethodMap1("ScoreboardPlayerScore", "clearScore", "reset");
		BuildTools.addMethodMap1("ServerWorld|World", "containsFluid", "containsAnyLiquid");
		BuildTools.addMethodMap1("ServerWorld|World", "getTime", "getGameTime");
		BuildTools.addMethodMap1("ServerWorld|World", "isAir", "isEmptyBlock");
		BuildTools.addMethodMap1("ServerWorld|World", "isSavingDisabled", "noSave");
		BuildTools.addMethodMap1("ServerWorld|World", "isWater", "isWaterAt");
		BuildTools.addMethodMap1("ServerWorld|World", "spawnEntity", "addFreshEntity");
		BuildTools.addMethodMap1("ServerWorld|World", "updateNeighbors", "updateNeighborsAt");
		BuildTools.addMethodMap1("Vector3d", "crossProduct", "cross");
		BuildTools.addMethodMap1("Vector3d", "dotProduct", "dot");
		BuildTools.addMethodMap1("Vector3d", "floorAlongAxes", "align");
		BuildTools.addMethodMap1("Vector3d", "getX", "x");
		BuildTools.addMethodMap1("Vector3d", "getY", "y");
		BuildTools.addMethodMap1("Vector3d", "getZ", "z");
		BuildTools.addMethodMap1("Vector3d", "lengthSquared", "lengthSqr");
		BuildTools.addMethodMap1("Vector3d", "of", "atLowerCornerOf");
		BuildTools.addMethodMap1("Vector3d", "ofBottomCenter", "atBottomCenterOf");
		BuildTools.addMethodMap1("Vector3d", "relativize", "vectorTo");
		BuildTools.addMethodMap1("Vector3d", "rotateX", "xRot");
		BuildTools.addMethodMap1("Vector3d", "rotateY", "yRot");
		BuildTools.addMethodMap1("Vector3d", "rotateZ", "zRot");
		BuildTools.addMethodMap1("Vector3f", "getX", "x");
		BuildTools.addMethodMap1("Vector3f", "getY", "y");
		BuildTools.addMethodMap1("Vector3f", "getZ", "z");
		BuildTools.addMethodMap1("Vector3i", "crossProduct", "cross");
		BuildTools.addMethodMap1("Vector3i", "down", "above");
		BuildTools.addMethodMap1("Vector3i", "up", "below");
		BuildTools.addMethodMap2("BlockItem|Item", "hasRecipeRemainder", "public boolean ()", "hasCraftingRemainingItem");
		BuildTools.addMethodMap2("BlockPos", "add", "public BlockPos (Vector3i)", "offset");
		BuildTools.addMethodMap2("Direction", "rotateYClockwise", "public Direction ()", "getClockWise");
		BuildTools.addMethodMap2("Direction", "rotateYCounterclockwise", "public Direction ()", "getCounterClockWise");
		BuildTools.addMethodMap2("Entity|PlayerEntity|ServerPlayerEntity", "addVelocity", "public void (double,double,double)", "push");
		BuildTools.addMethodMap2("Entity|PlayerEntity|ServerPlayerEntity", "getPitch", "public float (float)", "getViewXRot");
		BuildTools.addMethodMap2("Entity|PlayerEntity|ServerPlayerEntity", "getPosition", "public Vector3d ()", "getPos", "position");
		BuildTools.addMethodMap2("Entity|PlayerEntity|ServerPlayerEntity", "getYaw", "public float (float)", "getViewYRot");
		BuildTools.addMethodMap2("Entity|PlayerEntity|ServerPlayerEntity", "pushAwayFrom", "public void (Entity)", "push");
		BuildTools.addMethodMap2("ServerWorld|World", "isChunkLoaded", "public boolean (int,int)", "hasChunk");
		BuildTools.addMethodMap2("ServerWorld|World", "isSavingDisabled", "public boolean ()", "noSave");
		BuildTools.addMethodMap2("ServerWorld|World|WorldView", "isClient", "public boolean ()", "isClientSide");
		BuildTools.blacklist("BlockEntityType", "get", "public T (BlockView,BlockPos)");
		BuildTools.blacklist("CompoundTag", "getType", "public byte ()");
		BuildTools.blacklist("EntityType", "create", "public T (World)");
	}
}
